name = "hal-9000-proxy"
main = "functions/api/worker.js"
compatibility_date = "2025-08-01"

[vars]
# Define environment variables here if needed

# [env.production]
# Production-specific settings (optional)

# 
[[kv_namespaces]]
binding = "RESUME"
id = "44cf3d9bd8454125b1be172fcc4b7c3c"