name = "markmcfadden-proxy"
main = "functions/api/worker.js"
compatibility_date = "2025-08-01"

[vars]
# Define environment variables here if needed

# [env.production]
# Production-specific settings (optional)

# 
[[kv_namespaces]]
binding = "RESUME"
id = "4d4c99e8ad434f02a4a401b6ba1a3931"